-- Adds personnel accounts, assignment support, and personnel login RPCs.
-- Safe to run multiple times.

begin;

create extension if not exists pgcrypto with schema extensions;

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  if to_jsonb(new) ? 'updated_at' then
    new := jsonb_populate_record(new, jsonb_build_object('updated_at', now()));
  end if;
  return new;
end;
$$;

alter table public.reports
  add column if not exists assigned_personnel text,
  add column if not exists assigned_personnel_id bigint;

create table if not exists public.personnel (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  full_name text not null,
  team_id bigint references public.teams(id) on delete set null,
  is_active boolean not null default true
);

alter table public.personnel
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists full_name text,
  add column if not exists team_id bigint,
  add column if not exists is_active boolean not null default true,
  add column if not exists email text,
  add column if not exists password_hash text,
  add column if not exists last_login_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'personnel_team_id_fkey'
  ) then
    alter table public.personnel
      add constraint personnel_team_id_fkey
      foreign key (team_id) references public.teams(id) on delete set null;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_indexes
    where indexname = 'personnel_email_unique_idx'
  ) then
    create unique index personnel_email_unique_idx
      on public.personnel (lower(email))
      where nullif(btrim(email), '') is not null;
  end if;
end
$$;

alter table public.personnel enable row level security;
drop policy if exists "Allow public to view personnel" on public.personnel;
create policy "Allow public to view personnel" on public.personnel
  for select using (true);
drop policy if exists "Allow authenticated users to manage personnel" on public.personnel;
create policy "Allow authenticated users to manage personnel" on public.personnel
  for all using (true);

grant all on table public.personnel to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;

drop trigger if exists set_personnel_updated_at on public.personnel;
create trigger set_personnel_updated_at
before update on public.personnel
for each row
execute function public.update_updated_at_column();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'reports_assigned_personnel_id_fkey'
  ) then
    alter table public.reports
      add constraint reports_assigned_personnel_id_fkey
      foreign key (assigned_personnel_id) references public.personnel(id) on delete set null;
  end if;
end
$$;

create index if not exists reports_assigned_personnel_id_idx
  on public.reports (assigned_personnel_id);

create table if not exists public.report_personnel_assignments (
  report_id bigint not null,
  personnel_id bigint not null,
  assignment_status text not null default 'assigned',
  assigned_at timestamptz not null default now(),
  done_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.report_personnel_assignments
  add column if not exists report_id bigint,
  add column if not exists personnel_id bigint,
  add column if not exists assignment_status text not null default 'assigned',
  add column if not exists assigned_at timestamptz not null default now(),
  add column if not exists done_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'report_personnel_assignments_pkey'
  ) then
    alter table public.report_personnel_assignments
      add constraint report_personnel_assignments_pkey primary key (report_id, personnel_id);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'report_personnel_assignments_report_id_fkey'
  ) then
    alter table public.report_personnel_assignments
      add constraint report_personnel_assignments_report_id_fkey
      foreign key (report_id) references public.reports(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'report_personnel_assignments_personnel_id_fkey'
  ) then
    alter table public.report_personnel_assignments
      add constraint report_personnel_assignments_personnel_id_fkey
      foreign key (personnel_id) references public.personnel(id) on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'report_personnel_assignments_status_check'
  ) then
    alter table public.report_personnel_assignments
      add constraint report_personnel_assignments_status_check
      check (assignment_status in ('assigned', 'done'));
  end if;
end
$$;

create index if not exists report_personnel_assignments_report_id_idx
  on public.report_personnel_assignments (report_id);

create index if not exists report_personnel_assignments_personnel_id_idx
  on public.report_personnel_assignments (personnel_id);

create index if not exists report_personnel_assignments_status_idx
  on public.report_personnel_assignments (assignment_status);

insert into public.report_personnel_assignments (
  report_id,
  personnel_id,
  assignment_status,
  assigned_at,
  created_at,
  updated_at
)
select
  r.id,
  p.id,
  'assigned',
  coalesce(r.updated_at, r.created_at, now()),
  coalesce(r.created_at, now()),
  coalesce(r.updated_at, r.created_at, now())
from public.reports r
inner join public.personnel p
  on p.id = r.assigned_personnel_id
where r.assigned_personnel_id is not null
on conflict (report_id, personnel_id) do nothing;

alter table public.report_personnel_assignments enable row level security;
drop policy if exists "Allow public to view report personnel assignments" on public.report_personnel_assignments;
create policy "Allow public to view report personnel assignments" on public.report_personnel_assignments
  for select using (true);
drop policy if exists "Allow authenticated users to manage report personnel assignments" on public.report_personnel_assignments;
create policy "Allow authenticated users to manage report personnel assignments" on public.report_personnel_assignments
  for all using (true) with check (true);

grant all on table public.report_personnel_assignments to anon, authenticated, service_role;

drop trigger if exists set_report_personnel_assignments_updated_at on public.report_personnel_assignments;
create trigger set_report_personnel_assignments_updated_at
before update on public.report_personnel_assignments
for each row
execute function public.update_updated_at_column();

create or replace function public.refresh_report_personnel_summary(
  p_report_id bigint
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_first_personnel_id bigint;
  v_personnel_names text;
begin
  select rpa.personnel_id
  into v_first_personnel_id
  from public.report_personnel_assignments rpa
  where rpa.report_id = p_report_id
  order by rpa.assigned_at asc, rpa.personnel_id asc
  limit 1;

  select string_agg(p.full_name, ', ' order by p.full_name)
  into v_personnel_names
  from public.report_personnel_assignments rpa
  inner join public.personnel p
    on p.id = rpa.personnel_id
  where rpa.report_id = p_report_id;

  update public.reports r
  set
    assigned_personnel_id = v_first_personnel_id,
    assigned_personnel = nullif(btrim(coalesce(v_personnel_names, '')), ''),
    updated_at = now()
  where r.id = p_report_id;
end;
$$;

create or replace function public.create_personnel_account(
  p_full_name text,
  p_email text,
  p_password text,
  p_team_id bigint
)
returns table (
  id bigint,
  full_name text,
  email text,
  team_id bigint,
  team_name text,
  is_active boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_full_name text := nullif(btrim(coalesce(p_full_name, '')), '');
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_team public.teams%rowtype;
  v_personnel public.personnel%rowtype;
begin
  if v_full_name is null then
    raise exception 'Personnel full name is required';
  end if;

  if v_email = '' or position('@' in v_email) = 0 then
    raise exception 'Valid personnel email is required';
  end if;

  if length(coalesce(p_password, '')) < 8 then
    raise exception 'Personnel password must be at least 8 characters';
  end if;

  select *
  into v_team
  from public.teams t
  where t.id = p_team_id
  limit 1;

  if v_team.id is null then
    raise exception 'Selected team was not found';
  end if;

  if exists (
    select 1
    from public.personnel p
    where lower(btrim(coalesce(p.email, ''))) = v_email
  ) then
    raise exception 'Personnel email is already in use';
  end if;

  insert into public.personnel (
    full_name,
    email,
    password_hash,
    team_id,
    is_active
  )
  values (
    v_full_name,
    v_email,
    extensions.crypt(p_password, extensions.gen_salt('bf', 10)),
    v_team.id,
    true
  )
  returning * into v_personnel;

  return query
  select
    v_personnel.id,
    v_personnel.full_name,
    v_personnel.email,
    v_personnel.team_id,
    v_team.name,
    v_personnel.is_active,
    v_personnel.created_at;
end;
$$;

create or replace function public.login_personnel_account(
  p_email text,
  p_password text
)
returns table (
  id bigint,
  full_name text,
  email text,
  team_id bigint,
  team_name text,
  is_active boolean,
  created_at timestamptz,
  last_login_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_personnel public.personnel%rowtype;
  v_team_name text;
begin
  if v_email = '' or coalesce(p_password, '') = '' then
    raise exception 'Invalid email or password';
  end if;

  select p.*
  into v_personnel
  from public.personnel p
  where lower(btrim(coalesce(p.email, ''))) = v_email
  limit 1;

  if v_personnel.id is null then
    raise exception 'Invalid email or password';
  end if;

  if coalesce(v_personnel.is_active, false) = false then
    raise exception 'This personnel account is inactive';
  end if;

  if v_personnel.password_hash is null
     or extensions.crypt(p_password, v_personnel.password_hash) <> v_personnel.password_hash then
    raise exception 'Invalid email or password';
  end if;

  update public.personnel as p
  set
    last_login_at = now(),
    updated_at = now()
  where p.id = v_personnel.id
  returning * into v_personnel;

  select t.name
  into v_team_name
  from public.teams t
  where t.id = v_personnel.team_id
  limit 1;

  return query
  select
    v_personnel.id,
    v_personnel.full_name,
    v_personnel.email,
    v_personnel.team_id,
    v_team_name,
    v_personnel.is_active,
    v_personnel.created_at,
    v_personnel.last_login_at;
end;
$$;

drop function if exists public.assign_report_personnel(bigint, bigint);
drop function if exists public.assign_report_personnel(bigint, bigint, jsonb);

create or replace function public.assign_report_personnel(
  p_report_id bigint,
  p_personnel_id bigint default null,
  p_personnel_ids jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_personnel public.personnel%rowtype;
  v_report public.reports%rowtype;
  v_personnel_team_name text;
  v_selected_ids bigint[] := array[]::bigint[];
  v_selected_personnel_id bigint;
  v_result jsonb;
begin
  if p_report_id is null then
    raise exception 'Report ID is required';
  end if;

  select r.*
  into v_report
  from public.reports r
  where r.id = p_report_id
  limit 1;

  if v_report.id is null then
    raise exception 'Report with ID % not found', p_report_id;
  end if;

  if p_personnel_ids is not null then
    if jsonb_typeof(p_personnel_ids) <> 'array' then
      raise exception 'Personnel IDs must be an array';
    end if;

    select coalesce(array_agg(distinct raw.value::bigint), array[]::bigint[])
    into v_selected_ids
    from jsonb_array_elements_text(p_personnel_ids) as raw(value)
    where nullif(btrim(raw.value), '') is not null;
  elsif p_personnel_id is not null then
    v_selected_ids := array[p_personnel_id];
  end if;

  if coalesce(array_length(v_selected_ids, 1), 0) > 0 then
    if nullif(btrim(coalesce(v_report.assigned_team, '')), '') is null then
      raise exception 'Assign a team to the report before assigning personnel';
    end if;

    foreach v_selected_personnel_id in array v_selected_ids loop
      select *
      into v_personnel
      from public.personnel p
      where p.id = v_selected_personnel_id
      limit 1;

      if v_personnel.id is null then
        raise exception 'Selected personnel was not found';
      end if;

      if coalesce(v_personnel.is_active, false) = false then
        raise exception 'Selected personnel is inactive';
      end if;

      select t.name
      into v_personnel_team_name
      from public.teams t
      where t.id = v_personnel.team_id
      limit 1;

      if nullif(btrim(coalesce(v_personnel_team_name, '')), '') is null then
        raise exception 'Selected personnel is not linked to a team';
      end if;

      if not exists (
        select 1
        from unnest(string_to_array(coalesce(v_report.assigned_team, ''), ',')) as assigned_team_name
        where lower(btrim(assigned_team_name)) = lower(btrim(v_personnel_team_name))
      ) then
        raise exception 'Selected personnel does not belong to an assigned team for this report';
      end if;
    end loop;
  end if;

  delete from public.report_personnel_assignments rpa
  where rpa.report_id = p_report_id
    and not (rpa.personnel_id = any(v_selected_ids));

  if coalesce(array_length(v_selected_ids, 1), 0) > 0 then
    insert into public.report_personnel_assignments (
      report_id,
      personnel_id,
      assignment_status,
      assigned_at,
      done_at,
      created_at,
      updated_at
    )
    select
      p_report_id,
      selected_personnel_id,
      'assigned',
      now(),
      null,
      now(),
      now()
    from unnest(v_selected_ids) as selected_personnel_id
    on conflict (report_id, personnel_id) do update
    set updated_at = now();
  end if;

  perform public.refresh_report_personnel_summary(p_report_id);

  select to_jsonb(r.*)
  into v_result
  from public.reports r
  where r.id = p_report_id
  limit 1;

  return v_result;
end;
$$;

drop function if exists public.mark_personnel_assignment_done(bigint, bigint);

create or replace function public.mark_personnel_assignment_done(
  p_report_id bigint,
  p_personnel_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_result jsonb;
  v_updated_report_id bigint;
begin
  if p_report_id is null then
    raise exception 'Report ID is required';
  end if;

  if p_personnel_id is null then
    raise exception 'Personnel ID is required';
  end if;

  update public.report_personnel_assignments rpa
  set
    assignment_status = 'done',
    done_at = now(),
    updated_at = now()
  where rpa.report_id = p_report_id
    and rpa.personnel_id = p_personnel_id
  returning rpa.report_id into v_updated_report_id;

  if v_updated_report_id is null then
    raise exception 'Personnel assignment was not found';
  end if;

  -- Automatically mark the report as resolved when a personnel marks it as done
  update public.reports
  set 
    status = 'resolved',
    resolved_at = now(),
    updated_at = now()
  where id = p_report_id;

  perform public.refresh_report_personnel_summary(p_report_id);

  select to_jsonb(r.*)
  into v_result
  from public.reports r
  where r.id = p_report_id
  limit 1;

  return v_result;
end;
$$;

revoke all on function public.create_personnel_account(text, text, text, bigint) from public;
revoke all on function public.login_personnel_account(text, text) from public;
revoke all on function public.assign_report_personnel(bigint, bigint, jsonb) from public;
revoke all on function public.mark_personnel_assignment_done(bigint, bigint) from public;

grant execute on function public.create_personnel_account(text, text, text, bigint) to anon, authenticated;
grant execute on function public.login_personnel_account(text, text) to anon, authenticated;
grant execute on function public.assign_report_personnel(bigint, bigint, jsonb) to anon, authenticated;
grant execute on function public.mark_personnel_assignment_done(bigint, bigint) to anon, authenticated;

commit;
