-- Full schema setup for SAMELCO system
-- Includes: customer_users (users), teams, reports, assigned_team_snapshots,
-- report_images, admin_users, notifications, report_status_history
-- Safe to run multiple times (Idempotent)

BEGIN;

-- ==========================================
-- 1. Setup & Extensions
-- ==========================================
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- Safe shared trigger helper used by tables with an updated_at column.
-- Defined early so existing triggers from previous runs won't fail on updates below.
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    IF to_jsonb(NEW) ? 'updated_at' THEN
        NEW := jsonb_populate_record(NEW, jsonb_build_object('updated_at', now()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 2. customer_users (User's "users" table)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.customer_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure all columns exist
ALTER TABLE public.customer_users
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS account_number text,
  ADD COLUMN IF NOT EXISTS contact_number text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

-- Unique constraints
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'customer_users_email_unique_idx') THEN
        CREATE UNIQUE INDEX customer_users_email_unique_idx ON public.customer_users (lower(email));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'customer_users_account_number_unique_idx') THEN
        CREATE UNIQUE INDEX customer_users_account_number_unique_idx ON public.customer_users (account_number) WHERE nullif(btrim(account_number), '') IS NOT NULL;
    END IF;
END
$$;

-- Customer Auth Functions
DROP FUNCTION IF EXISTS public.register_customer_user(text, text, text, text, text, text, text, text);
DROP FUNCTION IF EXISTS public.register_customer_user(text, text, text, text, text, text, text);

CREATE OR REPLACE FUNCTION public.register_customer_user(
  p_full_name text,
  p_email text,
  p_password text,
  p_account_number text default null,
  p_contact_number text default null,
  p_municipality text default null,
  p_barangay text default null
)
RETURNS TABLE (
  id bigint,
  full_name text,
  email text,
  account_number text,
  contact_number text,
  municipality text,
  barangay text,
  created_at timestamptz,
  last_login_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_account_number text := nullif(btrim(coalesce(p_account_number, '')), '');
  v_contact_number text := nullif(btrim(coalesce(p_contact_number, '')), '');
  v_municipality text := nullif(btrim(coalesce(p_municipality, '')), '');
  v_barangay text := nullif(btrim(coalesce(p_barangay, '')), '');
BEGIN
  IF btrim(coalesce(p_full_name, '')) = '' THEN
    RAISE EXCEPTION 'Full name is required';
  END IF;

  IF v_email = '' OR position('@' IN v_email) = 0 THEN
    RAISE EXCEPTION 'Valid email is required';
  END IF;

  IF length(coalesce(p_password, '')) < 8 THEN
    RAISE EXCEPTION 'Password must be at least 8 characters';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.customer_users cu
    WHERE lower(cu.email) = v_email
  ) THEN
    RAISE EXCEPTION 'Email is already registered';
  END IF;

  IF v_account_number IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.customer_users cu
    WHERE cu.account_number = v_account_number
  ) THEN
    RAISE EXCEPTION 'Account number is already registered';
  END IF;

  RETURN QUERY
  INSERT INTO public.customer_users AS cu (
    full_name,
    email,
    account_number,
    contact_number,
    municipality,
    barangay,
    password_hash
  )
  VALUES (
    btrim(p_full_name),
    v_email,
    v_account_number,
    v_contact_number,
    v_municipality,
    v_barangay,
    extensions.crypt(p_password, extensions.gen_salt('bf', 10))
  )
  RETURNING
    cu.id,
    cu.full_name,
    cu.email,
    cu.account_number,
    cu.contact_number,
    cu.municipality,
    cu.barangay,
    cu.created_at,
    cu.last_login_at;
END;
$$;

DROP FUNCTION IF EXISTS public.login_customer_user(text, text);

CREATE OR REPLACE FUNCTION public.login_customer_user(
  p_email text,
  p_password text
)
RETURNS TABLE (
  id bigint,
  full_name text,
  email text,
  account_number text,
  contact_number text,
  municipality text,
  barangay text,
  created_at timestamptz,
  last_login_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_user public.customer_users%rowtype;
BEGIN
  IF v_email = '' OR coalesce(p_password, '') = '' THEN
    RAISE EXCEPTION 'Invalid email or password';
  END IF;

  SELECT *
  INTO v_user
  FROM public.customer_users cu
  WHERE lower(btrim(cu.email)) = v_email
  LIMIT 1;

  IF v_user.id IS NULL THEN
    RAISE EXCEPTION 'Invalid email or password';
  END IF;

  IF v_user.is_active = false THEN
    RAISE EXCEPTION 'Account is inactive. Please contact support.';
  END IF;

  IF v_user.password_hash IS NULL
     OR extensions.crypt(p_password, v_user.password_hash) <> v_user.password_hash THEN
    RAISE EXCEPTION 'Invalid email or password';
  END IF;

  UPDATE public.customer_users
  SET last_login_at = now()
  WHERE customer_users.id = v_user.id
  RETURNING *
  INTO v_user;

  RETURN QUERY
  SELECT
    v_user.id,
    v_user.full_name,
    v_user.email,
    v_user.account_number,
    v_user.contact_number,
    v_user.municipality,
    v_user.barangay,
    v_user.created_at,
    v_user.last_login_at;
END;
$$;

REVOKE ALL ON FUNCTION public.register_customer_user(text, text, text, text, text, text, text) FROM public;
REVOKE ALL ON FUNCTION public.login_customer_user(text, text) FROM public;

GRANT EXECUTE ON FUNCTION public.register_customer_user(text, text, text, text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.login_customer_user(text, text) TO anon, authenticated;

DROP FUNCTION IF EXISTS public.get_customer_email_by_name(text);

CREATE OR REPLACE FUNCTION public.get_customer_email_by_name(
  p_full_name text
)
RETURNS TABLE (
  email text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT cu.email
  FROM public.customer_users cu
  WHERE lower(cu.full_name) = lower(btrim(p_full_name))
    AND cu.is_active = true
  LIMIT 1;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_customer_email_by_name(text) TO anon, authenticated;

-- Enable RLS
ALTER TABLE public.customer_users ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3. teams
-- ==========================================
CREATE TABLE IF NOT EXISTS public.teams (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.teams
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS dashboard_email text,
  ADD COLUMN IF NOT EXISTS has_dashboard_login boolean not null default false;

-- Unique constraint on name
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'teams_name_key') THEN
        ALTER TABLE public.teams ADD CONSTRAINT teams_name_key UNIQUE (name);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'teams_dashboard_email_unique_idx') THEN
        CREATE UNIQUE INDEX teams_dashboard_email_unique_idx
            ON public.teams (lower(dashboard_email))
            WHERE nullif(btrim(dashboard_email), '') IS NOT NULL;
    END IF;
END
$$;

INSERT INTO public.teams (name, description, is_active)
VALUES
    ('Line Crew A', 'Default line response team.', true),
    ('Line Crew B', 'Secondary line response team.', true),
    ('Maintenance', 'Maintenance response team.', true),
    ('Inspection', 'Inspection and validation team.', true)
ON CONFLICT (name) DO UPDATE
SET
    is_active = EXCLUDED.is_active,
    description = COALESCE(public.teams.description, EXCLUDED.description);

UPDATE public.teams
SET
    dashboard_email = lower(nullif(btrim(dashboard_email), '')),
    has_dashboard_login = CASE
        WHEN nullif(btrim(dashboard_email), '') IS NOT NULL THEN true
        ELSE false
    END
WHERE
    dashboard_email IS DISTINCT FROM lower(nullif(btrim(dashboard_email), ''))
    OR has_dashboard_login IS DISTINCT FROM CASE
        WHEN nullif(btrim(dashboard_email), '') IS NOT NULL THEN true
        ELSE false
    END;

-- Enable RLS on teams table
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- 1. Allow anyone to view active teams
DROP POLICY IF EXISTS "Allow public to view teams" ON public.teams;
CREATE POLICY "Allow public to view teams" ON public.teams
    FOR SELECT USING (true);

-- 2. Allow authenticated users (Admins) to manage teams
DROP POLICY IF EXISTS "Allow authenticated users to insert teams" ON public.teams;
CREATE POLICY "Allow authenticated users to insert teams" ON public.teams
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to update teams" ON public.teams;
CREATE POLICY "Allow authenticated users to update teams" ON public.teams
    FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated users to delete teams" ON public.teams;
CREATE POLICY "Allow authenticated users to delete teams" ON public.teams
    FOR DELETE USING (true);

-- Ensure permissions
GRANT ALL ON TABLE public.teams TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Team dashboard credentials
CREATE TABLE IF NOT EXISTS public.team_dashboard_accounts (
  team_id bigint primary key,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

ALTER TABLE public.team_dashboard_accounts
  ADD COLUMN IF NOT EXISTS team_id bigint,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_dashboard_accounts_pkey') THEN
        ALTER TABLE public.team_dashboard_accounts
            ADD CONSTRAINT team_dashboard_accounts_pkey PRIMARY KEY (team_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'team_dashboard_accounts_team_id_fkey') THEN
        ALTER TABLE public.team_dashboard_accounts
            ADD CONSTRAINT team_dashboard_accounts_team_id_fkey
            FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;
    END IF;
END
$$;

GRANT ALL ON TABLE public.team_dashboard_accounts TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ==========================================
-- 4. reports
-- ==========================================
CREATE TABLE IF NOT EXISTS public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.reports
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS contact text,
  ADD COLUMN IF NOT EXISTS location_text text,
  ADD COLUMN IF NOT EXISTS issue_type text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS latitude float8,
  ADD COLUMN IF NOT EXISTS longitude float8,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS status text not null default 'pending',
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS is_urgent boolean default false,
  ADD COLUMN IF NOT EXISTS queue_number bigint,
  ADD COLUMN IF NOT EXISTS assigned_team text,
  ADD COLUMN IF NOT EXISTS assigned_personnel text,
  ADD COLUMN IF NOT EXISTS assigned_personnel_id bigint;

UPDATE public.reports
SET assigned_team = nullif(btrim(assigned_team), '')
WHERE assigned_team IS DISTINCT FROM nullif(btrim(assigned_team), '');

UPDATE public.reports
SET assigned_personnel = nullif(btrim(assigned_personnel), '')
WHERE assigned_personnel IS DISTINCT FROM nullif(btrim(assigned_personnel), '');

INSERT INTO public.teams (name, is_active)
SELECT DISTINCT nullif(btrim(assigned_team), ''), true
FROM public.reports
WHERE nullif(btrim(assigned_team), '') IS NOT NULL
ON CONFLICT (name) DO UPDATE
SET is_active = EXCLUDED.is_active;

-- Add constraints and defaults
DO $$
BEGIN
    -- Status check constraint
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reports_status_check') THEN
        ALTER TABLE public.reports ADD CONSTRAINT reports_status_check CHECK (status in ('pending', 'ontheway', 'resolved'));
    END IF;

    -- Remove FK to teams to support multiple comma-separated teams
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reports_assigned_team_fkey') THEN
        ALTER TABLE public.reports DROP CONSTRAINT reports_assigned_team_fkey;
    END IF;
END
$$;

-- Handle queue_number sequence logic
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'reports_queue_number_seq') THEN
        CREATE SEQUENCE public.reports_queue_number_seq;
    END IF;
END
$$;

-- Set default value for queue_number if not already set
ALTER TABLE public.reports 
    ALTER COLUMN queue_number SET DEFAULT nextval('public.reports_queue_number_seq');

-- Ensure queue_number is unique
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'reports_queue_number_unique_idx') THEN
        CREATE UNIQUE INDEX reports_queue_number_unique_idx ON public.reports (queue_number);
    END IF;
END
$$;

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. assigned_team_snapshots
-- ==========================================
CREATE TABLE IF NOT EXISTS public.assigned_team_snapshots (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.assigned_team_snapshots
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS report_created_at timestamptz,
  ADD COLUMN IF NOT EXISTS snapshot_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS captured_at timestamptz,
  ADD COLUMN IF NOT EXISTS queue_number bigint,
  ADD COLUMN IF NOT EXISTS assigned_team text,
  ADD COLUMN IF NOT EXISTS team_name text,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS municipality text,
  ADD COLUMN IF NOT EXISTS barangay text,
  ADD COLUMN IF NOT EXISTS location_text text,
  ADD COLUMN IF NOT EXISTS issue_type text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS latitude float8,
  ADD COLUMN IF NOT EXISTS longitude float8,
  ADD COLUMN IF NOT EXISTS source text,
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS contact text,
  ADD COLUMN IF NOT EXISTS is_urgent boolean not null default false,
  ADD COLUMN IF NOT EXISTS resolved_at timestamptz,
  ADD COLUMN IF NOT EXISTS remarks text;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_report_id_fkey') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_report_id_idx
  ON public.assigned_team_snapshots (report_id);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_assigned_team_idx
  ON public.assigned_team_snapshots (assigned_team);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_team_name_idx
  ON public.assigned_team_snapshots (team_name);

CREATE INDEX IF NOT EXISTS assigned_team_snapshots_snapshot_at_idx
  ON public.assigned_team_snapshots (snapshot_at DESC);

WITH report_id_ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY report_id
            ORDER BY coalesce(snapshot_at, updated_at, created_at) DESC, id DESC
        ) AS rn
    FROM public.assigned_team_snapshots
    WHERE report_id IS NOT NULL
)
DELETE FROM public.assigned_team_snapshots s
USING report_id_ranked r
WHERE s.id = r.id
  AND r.rn > 1;

WITH queue_number_ranked AS (
    SELECT
        id,
        row_number() OVER (
            PARTITION BY queue_number
            ORDER BY coalesce(snapshot_at, updated_at, created_at) DESC, id DESC
        ) AS rn
    FROM public.assigned_team_snapshots
    WHERE queue_number IS NOT NULL
)
DELETE FROM public.assigned_team_snapshots s
USING queue_number_ranked q
WHERE s.id = q.id
  AND q.rn > 1;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_report_id_key') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_report_id_key UNIQUE (report_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'assigned_team_snapshots_queue_number_key') THEN
        ALTER TABLE public.assigned_team_snapshots ADD CONSTRAINT assigned_team_snapshots_queue_number_key UNIQUE (queue_number);
    END IF;
END
$$;

-- Keep either legacy team field name populated.
CREATE OR REPLACE FUNCTION public.sync_assigned_team_snapshot_team_fields()
RETURNS TRIGGER AS $$
BEGIN
    IF nullif(btrim(coalesce(NEW.assigned_team, '')), '') IS NULL THEN
        NEW.assigned_team := nullif(btrim(coalesce(NEW.team_name, '')), '');
    END IF;
    IF nullif(btrim(coalesce(NEW.team_name, '')), '') IS NULL THEN
        NEW.team_name := nullif(btrim(coalesce(NEW.assigned_team, '')), '');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_assigned_team_snapshot_team_fields ON public.assigned_team_snapshots;
CREATE TRIGGER sync_assigned_team_snapshot_team_fields
    BEFORE INSERT OR UPDATE ON public.assigned_team_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_assigned_team_snapshot_team_fields();

-- ==========================================
-- 6. report_images
-- ==========================================
CREATE TABLE IF NOT EXISTS public.report_images (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.report_images
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS image_url text;

-- FK to reports
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_images_report_id_fkey') THEN
        ALTER TABLE public.report_images ADD CONSTRAINT report_images_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.report_images ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 7. admin_users
-- ==========================================
CREATE TABLE IF NOT EXISTS public.admin_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.admin_users
  ADD COLUMN IF NOT EXISTS username text,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS role text not null default 'staff',
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

-- Constraints
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_username_key') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_username_key UNIQUE (username);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_email_key') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_email_key UNIQUE (email);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'admin_users_role_check') THEN
        ALTER TABLE public.admin_users ADD CONSTRAINT admin_users_role_check CHECK (role in ('admin', 'staff', 'viewer'));
    END IF;
END
$$;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 8. notifications
-- ==========================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS user_id bigint,
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS is_read boolean not null default false,
  ADD COLUMN IF NOT EXISTS type text default 'info';

-- FK to customer_users
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'notifications_user_id_fkey') THEN
        ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.customer_users(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 9. report_status_history
-- ==========================================
CREATE TABLE IF NOT EXISTS public.report_status_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now() -- This will serve as changed_at if not provided, but we usually set it explicitly
);

ALTER TABLE public.report_status_history
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS previous_status text,
  ADD COLUMN IF NOT EXISTS new_status text,
  ADD COLUMN IF NOT EXISTS changed_by text,
  ADD COLUMN IF NOT EXISTS changed_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS remarks text;

-- FK to reports
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_status_history_report_id_fkey') THEN
        ALTER TABLE public.report_status_history ADD CONSTRAINT report_status_history_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

ALTER TABLE public.report_status_history ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 10. RPC functions
-- ==========================================

DROP FUNCTION IF EXISTS public.set_report_status(bigint, text, text);

CREATE OR REPLACE FUNCTION public.set_report_status(
    p_report_id bigint,
    p_status text,
    p_team_name text DEFAULT null
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_status text := lower(btrim(coalesce(p_status, '')));
    v_team_name text := nullif(btrim(coalesce(p_team_name, '')), '');
    v_result jsonb;
BEGIN
    IF p_report_id IS NULL THEN
        RAISE EXCEPTION 'Report ID is required';
    END IF;

    IF v_status NOT IN ('pending', 'ontheway', 'resolved') THEN
        RAISE EXCEPTION 'Invalid status "%"', p_status;
    END IF;

    -- Multiple teams support
    -- Validation is handled by application logic or allowed as free text.

    UPDATE public.reports
    SET
        status = v_status,
        resolved_at = CASE WHEN v_status = 'resolved' THEN now() ELSE null END,
        assigned_team = coalesce(v_team_name, assigned_team),
        updated_at = now()
    WHERE id = p_report_id
    RETURNING to_jsonb(reports.*) INTO v_result;

    IF v_result IS NULL THEN
        RAISE EXCEPTION 'Report with ID % not found', p_report_id;
    END IF;

    RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.set_report_status(bigint, text, text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.create_team_with_dashboard_account(
    p_name text,
    p_dashboard_email text,
    p_password text,
    p_description text DEFAULT null
)
RETURNS TABLE (
    id bigint,
    name text,
    description text,
    is_active boolean,
    dashboard_email text,
    has_dashboard_login boolean,
    created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_name text := nullif(btrim(coalesce(p_name, '')), '');
    v_email text := lower(btrim(coalesce(p_dashboard_email, '')));
    v_description text := nullif(btrim(coalesce(p_description, '')), '');
    v_team public.teams%ROWTYPE;
BEGIN
    IF v_name IS NULL THEN
        RAISE EXCEPTION 'Team name is required';
    END IF;

    IF v_email = '' OR position('@' IN v_email) = 0 THEN
        RAISE EXCEPTION 'Valid dashboard email is required';
    END IF;

    IF length(coalesce(p_password, '')) < 8 THEN
        RAISE EXCEPTION 'Dashboard password must be at least 8 characters';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.teams t
        WHERE lower(btrim(coalesce(t.name, ''))) = lower(v_name)
    ) THEN
        RAISE EXCEPTION 'A team with this name already exists';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.teams t
        WHERE lower(btrim(coalesce(t.dashboard_email, ''))) = v_email
    ) THEN
        RAISE EXCEPTION 'Dashboard email is already in use';
    END IF;

    INSERT INTO public.teams (
        name,
        description,
        is_active,
        dashboard_email,
        has_dashboard_login
    )
    VALUES (
        v_name,
        v_description,
        true,
        v_email,
        true
    )
    RETURNING * INTO v_team;

    INSERT INTO public.team_dashboard_accounts (
        team_id,
        password_hash
    )
    VALUES (
        v_team.id,
        extensions.crypt(p_password, extensions.gen_salt('bf', 10))
    );

    RETURN QUERY
    SELECT
        v_team.id,
        v_team.name,
        v_team.description,
        v_team.is_active,
        v_team.dashboard_email,
        v_team.has_dashboard_login,
        v_team.created_at;
END;
$$;

DROP FUNCTION IF EXISTS public.login_team_dashboard(text, text);

CREATE OR REPLACE FUNCTION public.login_team_dashboard(
    p_email text,
    p_password text
)
RETURNS TABLE (
    team_id bigint,
    team_name text,
    dashboard_email text,
    description text,
    is_active boolean,
    created_at timestamptz,
    last_login_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_email text := lower(btrim(coalesce(p_email, '')));
    v_team_id bigint;
    v_team_name text;
    v_dashboard_email text;
    v_description text;
    v_is_active boolean;
    v_created_at timestamptz;
    v_password_hash text;
    v_last_login_at timestamptz;
BEGIN
    IF v_email = '' OR coalesce(p_password, '') = '' THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    SELECT
        t.id,
        t.name,
        t.dashboard_email,
        t.description,
        t.is_active,
        t.created_at,
        a.password_hash,
        a.last_login_at
    INTO
        v_team_id,
        v_team_name,
        v_dashboard_email,
        v_description,
        v_is_active,
        v_created_at,
        v_password_hash,
        v_last_login_at
    FROM public.teams t
    INNER JOIN public.team_dashboard_accounts a
        ON a.team_id = t.id
    WHERE lower(btrim(coalesce(t.dashboard_email, ''))) = v_email
      AND coalesce(t.has_dashboard_login, false) = true
    LIMIT 1;

    IF v_team_id IS NULL THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    IF coalesce(v_is_active, false) = false THEN
        RAISE EXCEPTION 'This team dashboard is inactive';
    END IF;

    IF v_password_hash IS NULL
       OR extensions.crypt(p_password, v_password_hash) <> v_password_hash THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    UPDATE public.team_dashboard_accounts AS tda
    SET
        last_login_at = now(),
        updated_at = now()
    WHERE tda.team_id = v_team_id
    RETURNING tda.last_login_at INTO v_last_login_at;

    RETURN QUERY
    SELECT
        v_team_id,
        v_team_name,
        v_dashboard_email,
        v_description,
        v_is_active,
        v_created_at,
        v_last_login_at;
END;
$$;

REVOKE ALL ON FUNCTION public.create_team_with_dashboard_account(text, text, text, text) FROM public;
REVOKE ALL ON FUNCTION public.login_team_dashboard(text, text) FROM public;

GRANT EXECUTE ON FUNCTION public.create_team_with_dashboard_account(text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.login_team_dashboard(text, text) TO anon, authenticated;

-- ==========================================
-- 11. Triggers
-- ==========================================

-- Trigger for report_status_history
CREATE OR REPLACE FUNCTION public.log_report_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF (OLD.status IS DISTINCT FROM NEW.status) THEN
        INSERT INTO public.report_status_history (report_id, previous_status, new_status, changed_at)
        VALUES (NEW.id, OLD.status, NEW.status, now());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_report_status_change ON public.reports;
CREATE TRIGGER trigger_log_report_status_change
    AFTER UPDATE ON public.reports
    FOR EACH ROW
    EXECUTE FUNCTION public.log_report_status_change();

-- Trigger for updated_at columns
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    IF to_jsonb(NEW) ? 'updated_at' THEN
        NEW := jsonb_populate_record(NEW, jsonb_build_object('updated_at', now()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to customer_users
DROP TRIGGER IF EXISTS set_customer_users_updated_at ON public.customer_users;
CREATE TRIGGER set_customer_users_updated_at
    BEFORE UPDATE ON public.customer_users
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to teams
DROP TRIGGER IF EXISTS set_teams_updated_at ON public.teams;
CREATE TRIGGER set_teams_updated_at
    BEFORE UPDATE ON public.teams
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to team_dashboard_accounts
DROP TRIGGER IF EXISTS set_team_dashboard_accounts_updated_at ON public.team_dashboard_accounts;
CREATE TRIGGER set_team_dashboard_accounts_updated_at
    BEFORE UPDATE ON public.team_dashboard_accounts
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to reports
DROP TRIGGER IF EXISTS set_reports_updated_at ON public.reports;
CREATE TRIGGER set_reports_updated_at
    BEFORE UPDATE ON public.reports
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply updated_at trigger to assigned_team_snapshots
DROP TRIGGER IF EXISTS set_assigned_team_snapshots_updated_at ON public.assigned_team_snapshots;
CREATE TRIGGER set_assigned_team_snapshots_updated_at
    BEFORE UPDATE ON public.assigned_team_snapshots
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ==========================================
-- 12. personnel (The "tao" or members)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.personnel (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  full_name text not null,
  team_id bigint REFERENCES public.teams(id) ON DELETE SET NULL,
  is_active boolean not null default true
);

ALTER TABLE public.personnel
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS full_name text,
  ADD COLUMN IF NOT EXISTS team_id bigint,
  ADD COLUMN IF NOT EXISTS is_active boolean not null default true,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS password_hash text,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'personnel_team_id_fkey') THEN
        ALTER TABLE public.personnel
            ADD CONSTRAINT personnel_team_id_fkey
            FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'personnel_email_unique_idx') THEN
        CREATE UNIQUE INDEX personnel_email_unique_idx
            ON public.personnel (lower(email))
            WHERE nullif(btrim(email), '') IS NOT NULL;
    END IF;
END
$$;

ALTER TABLE public.personnel ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public to view personnel" ON public.personnel;
CREATE POLICY "Allow public to view personnel" ON public.personnel FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users to manage personnel" ON public.personnel;
CREATE POLICY "Allow authenticated users to manage personnel" ON public.personnel FOR ALL USING (true);
GRANT ALL ON TABLE public.personnel TO anon, authenticated, service_role;

DROP TRIGGER IF EXISTS set_personnel_updated_at ON public.personnel;
CREATE TRIGGER set_personnel_updated_at
    BEFORE UPDATE ON public.personnel
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reports_assigned_personnel_id_fkey') THEN
        ALTER TABLE public.reports
            ADD CONSTRAINT reports_assigned_personnel_id_fkey
            FOREIGN KEY (assigned_personnel_id) REFERENCES public.personnel(id) ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS reports_assigned_personnel_id_idx
    ON public.reports (assigned_personnel_id);

CREATE TABLE IF NOT EXISTS public.report_personnel_assignments (
  report_id bigint not null,
  personnel_id bigint not null,
  assignment_status text not null default 'assigned',
  assigned_at timestamptz not null default now(),
  done_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

ALTER TABLE public.report_personnel_assignments
  ADD COLUMN IF NOT EXISTS report_id bigint,
  ADD COLUMN IF NOT EXISTS personnel_id bigint,
  ADD COLUMN IF NOT EXISTS assignment_status text not null default 'assigned',
  ADD COLUMN IF NOT EXISTS assigned_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS done_at timestamptz,
  ADD COLUMN IF NOT EXISTS created_at timestamptz not null default now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz not null default now();

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_personnel_assignments_pkey') THEN
        ALTER TABLE public.report_personnel_assignments
            ADD CONSTRAINT report_personnel_assignments_pkey PRIMARY KEY (report_id, personnel_id);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_personnel_assignments_report_id_fkey') THEN
        ALTER TABLE public.report_personnel_assignments
            ADD CONSTRAINT report_personnel_assignments_report_id_fkey
            FOREIGN KEY (report_id) REFERENCES public.reports(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_personnel_assignments_personnel_id_fkey') THEN
        ALTER TABLE public.report_personnel_assignments
            ADD CONSTRAINT report_personnel_assignments_personnel_id_fkey
            FOREIGN KEY (personnel_id) REFERENCES public.personnel(id) ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'report_personnel_assignments_status_check') THEN
        ALTER TABLE public.report_personnel_assignments
            ADD CONSTRAINT report_personnel_assignments_status_check
            CHECK (assignment_status in ('assigned', 'done'));
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS report_personnel_assignments_report_id_idx
    ON public.report_personnel_assignments (report_id);

CREATE INDEX IF NOT EXISTS report_personnel_assignments_personnel_id_idx
    ON public.report_personnel_assignments (personnel_id);

CREATE INDEX IF NOT EXISTS report_personnel_assignments_status_idx
    ON public.report_personnel_assignments (assignment_status);

INSERT INTO public.report_personnel_assignments (
    report_id,
    personnel_id,
    assignment_status,
    assigned_at,
    created_at,
    updated_at
)
SELECT
    r.id,
    p.id,
    'assigned',
    coalesce(r.updated_at, r.created_at, now()),
    coalesce(r.created_at, now()),
    coalesce(r.updated_at, r.created_at, now())
FROM public.reports r
INNER JOIN public.personnel p
    ON p.id = r.assigned_personnel_id
WHERE r.assigned_personnel_id IS NOT NULL
ON CONFLICT (report_id, personnel_id) DO NOTHING;

ALTER TABLE public.report_personnel_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public to view report personnel assignments" ON public.report_personnel_assignments;
CREATE POLICY "Allow public to view report personnel assignments" ON public.report_personnel_assignments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow authenticated users to manage report personnel assignments" ON public.report_personnel_assignments;
CREATE POLICY "Allow authenticated users to manage report personnel assignments" ON public.report_personnel_assignments FOR ALL USING (true) WITH CHECK (true);
GRANT ALL ON TABLE public.report_personnel_assignments TO anon, authenticated, service_role;

DROP TRIGGER IF EXISTS set_report_personnel_assignments_updated_at ON public.report_personnel_assignments;
CREATE TRIGGER set_report_personnel_assignments_updated_at
    BEFORE UPDATE ON public.report_personnel_assignments
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.refresh_report_personnel_summary(
    p_report_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_first_personnel_id bigint;
    v_personnel_names text;
BEGIN
    SELECT rpa.personnel_id
    INTO v_first_personnel_id
    FROM public.report_personnel_assignments rpa
    WHERE rpa.report_id = p_report_id
    ORDER BY rpa.assigned_at ASC, rpa.personnel_id ASC
    LIMIT 1;

    SELECT string_agg(p.full_name, ', ' ORDER BY p.full_name)
    INTO v_personnel_names
    FROM public.report_personnel_assignments rpa
    INNER JOIN public.personnel p
        ON p.id = rpa.personnel_id
    WHERE rpa.report_id = p_report_id;

    UPDATE public.reports r
    SET
        assigned_personnel_id = v_first_personnel_id,
        assigned_personnel = nullif(btrim(coalesce(v_personnel_names, '')), ''),
        updated_at = now()
    WHERE r.id = p_report_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_personnel_account(
    p_full_name text,
    p_email text,
    p_password text,
    p_team_id bigint
)
RETURNS TABLE (
    id bigint,
    full_name text,
    email text,
    team_id bigint,
    team_name text,
    is_active boolean,
    created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_full_name text := nullif(btrim(coalesce(p_full_name, '')), '');
    v_email text := lower(btrim(coalesce(p_email, '')));
    v_team public.teams%ROWTYPE;
    v_personnel public.personnel%ROWTYPE;
BEGIN
    IF v_full_name IS NULL THEN
        RAISE EXCEPTION 'Personnel full name is required';
    END IF;

    IF v_email = '' OR position('@' IN v_email) = 0 THEN
        RAISE EXCEPTION 'Valid personnel email is required';
    END IF;

    IF length(coalesce(p_password, '')) < 8 THEN
        RAISE EXCEPTION 'Personnel password must be at least 8 characters';
    END IF;

    SELECT *
    INTO v_team
    FROM public.teams t
    WHERE t.id = p_team_id
    LIMIT 1;

    IF v_team.id IS NULL THEN
        RAISE EXCEPTION 'Selected team was not found';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM public.personnel p
        WHERE lower(btrim(coalesce(p.email, ''))) = v_email
    ) THEN
        RAISE EXCEPTION 'Personnel email is already in use';
    END IF;

    INSERT INTO public.personnel (
        full_name,
        email,
        password_hash,
        team_id,
        is_active
    )
    VALUES (
        v_full_name,
        v_email,
        extensions.crypt(p_password, extensions.gen_salt('bf', 10)),
        v_team.id,
        true
    )
    RETURNING * INTO v_personnel;

    RETURN QUERY
    SELECT
        v_personnel.id,
        v_personnel.full_name,
        v_personnel.email,
        v_personnel.team_id,
        v_team.name,
        v_personnel.is_active,
        v_personnel.created_at;
END;
$$;

DROP FUNCTION IF EXISTS public.login_personnel_account(text, text);

CREATE OR REPLACE FUNCTION public.login_personnel_account(
    p_email text,
    p_password text
)
RETURNS TABLE (
    id bigint,
    full_name text,
    email text,
    team_id bigint,
    team_name text,
    is_active boolean,
    created_at timestamptz,
    last_login_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_email text := lower(btrim(coalesce(p_email, '')));
    v_personnel public.personnel%ROWTYPE;
    v_team_name text;
BEGIN
    IF v_email = '' OR coalesce(p_password, '') = '' THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    SELECT p.*
    INTO v_personnel
    FROM public.personnel p
    WHERE lower(btrim(coalesce(p.email, ''))) = v_email
    LIMIT 1;

    IF v_personnel.id IS NULL THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    IF coalesce(v_personnel.is_active, false) = false THEN
        RAISE EXCEPTION 'This personnel account is inactive';
    END IF;

    IF v_personnel.password_hash IS NULL
       OR extensions.crypt(p_password, v_personnel.password_hash) <> v_personnel.password_hash THEN
        RAISE EXCEPTION 'Invalid email or password';
    END IF;

    UPDATE public.personnel AS p
    SET
        last_login_at = now(),
        updated_at = now()
    WHERE p.id = v_personnel.id
    RETURNING * INTO v_personnel;

    SELECT t.name
    INTO v_team_name
    FROM public.teams t
    WHERE t.id = v_personnel.team_id
    LIMIT 1;

    RETURN QUERY
    SELECT
        v_personnel.id,
        v_personnel.full_name,
        v_personnel.email,
        v_personnel.team_id,
        v_team_name,
        v_personnel.is_active,
        v_personnel.created_at,
        v_personnel.last_login_at;
END;
$$;

DROP FUNCTION IF EXISTS public.assign_report_personnel(bigint, bigint);
DROP FUNCTION IF EXISTS public.assign_report_personnel(bigint, bigint, jsonb);

CREATE OR REPLACE FUNCTION public.assign_report_personnel(
    p_report_id bigint,
    p_personnel_id bigint DEFAULT null,
    p_personnel_ids jsonb DEFAULT null
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_personnel public.personnel%ROWTYPE;
    v_report public.reports%ROWTYPE;
    v_personnel_team_name text;
    v_selected_ids bigint[] := ARRAY[]::bigint[];
    v_selected_personnel_id bigint;
    v_result jsonb;
BEGIN
    IF p_report_id IS NULL THEN
        RAISE EXCEPTION 'Report ID is required';
    END IF;

    SELECT r.*
    INTO v_report
    FROM public.reports r
    WHERE r.id = p_report_id
    LIMIT 1;

    IF v_report.id IS NULL THEN
        RAISE EXCEPTION 'Report with ID % not found', p_report_id;
    END IF;

    IF p_personnel_ids IS NOT NULL THEN
        IF jsonb_typeof(p_personnel_ids) <> 'array' THEN
            RAISE EXCEPTION 'Personnel IDs must be an array';
        END IF;

        SELECT coalesce(array_agg(DISTINCT raw.value::bigint), ARRAY[]::bigint[])
        INTO v_selected_ids
        FROM jsonb_array_elements_text(p_personnel_ids) AS raw(value)
        WHERE nullif(btrim(raw.value), '') IS NOT NULL;
    ELSIF p_personnel_id IS NOT NULL THEN
        v_selected_ids := ARRAY[p_personnel_id];
    END IF;

    IF coalesce(array_length(v_selected_ids, 1), 0) > 0 THEN
        IF nullif(btrim(coalesce(v_report.assigned_team, '')), '') IS NULL THEN
            RAISE EXCEPTION 'Assign a team to the report before assigning personnel';
        END IF;

        FOREACH v_selected_personnel_id IN ARRAY v_selected_ids LOOP
            SELECT *
            INTO v_personnel
            FROM public.personnel p
            WHERE p.id = v_selected_personnel_id
            LIMIT 1;

            IF v_personnel.id IS NULL THEN
                RAISE EXCEPTION 'Selected personnel was not found';
            END IF;

            IF coalesce(v_personnel.is_active, false) = false THEN
                RAISE EXCEPTION 'Selected personnel is inactive';
            END IF;

            SELECT t.name
            INTO v_personnel_team_name
            FROM public.teams t
            WHERE t.id = v_personnel.team_id
            LIMIT 1;

            IF nullif(btrim(coalesce(v_personnel_team_name, '')), '') IS NULL THEN
                RAISE EXCEPTION 'Selected personnel is not linked to a team';
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM unnest(string_to_array(coalesce(v_report.assigned_team, ''), ',')) AS assigned_team_name
                WHERE lower(btrim(assigned_team_name)) = lower(btrim(v_personnel_team_name))
            ) THEN
                RAISE EXCEPTION 'Selected personnel does not belong to an assigned team for this report';
            END IF;
        END LOOP;
    END IF;

    DELETE FROM public.report_personnel_assignments rpa
    WHERE rpa.report_id = p_report_id
      AND NOT (rpa.personnel_id = ANY(v_selected_ids));

    IF coalesce(array_length(v_selected_ids, 1), 0) > 0 THEN
        INSERT INTO public.report_personnel_assignments (
            report_id,
            personnel_id,
            assignment_status,
            assigned_at,
            done_at,
            created_at,
            updated_at
        )
        SELECT
            p_report_id,
            selected_personnel_id,
            'assigned',
            now(),
            null,
            now(),
            now()
        FROM unnest(v_selected_ids) AS selected_personnel_id
        ON CONFLICT (report_id, personnel_id) DO UPDATE
        SET updated_at = now();
    END IF;

    PERFORM public.refresh_report_personnel_summary(p_report_id);

    SELECT to_jsonb(r.*)
    INTO v_result
    FROM public.reports r
    WHERE r.id = p_report_id
    LIMIT 1;

    RETURN v_result;
END;
$$;

DROP FUNCTION IF EXISTS public.mark_personnel_assignment_done(bigint, bigint);

CREATE OR REPLACE FUNCTION public.mark_personnel_assignment_done(
    p_report_id bigint,
    p_personnel_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
    v_result jsonb;
    v_updated_report_id bigint;
BEGIN
    IF p_report_id IS NULL THEN
        RAISE EXCEPTION 'Report ID is required';
    END IF;

    IF p_personnel_id IS NULL THEN
        RAISE EXCEPTION 'Personnel ID is required';
    END IF;

    UPDATE public.report_personnel_assignments rpa
    SET
        assignment_status = 'done',
        done_at = now(),
        updated_at = now()
    WHERE rpa.report_id = p_report_id
      AND rpa.personnel_id = p_personnel_id
    RETURNING rpa.report_id INTO v_updated_report_id;

    IF v_updated_report_id IS NULL THEN
        RAISE EXCEPTION 'Personnel assignment was not found';
    END IF;

    PERFORM public.refresh_report_personnel_summary(p_report_id);

    SELECT to_jsonb(r.*)
    INTO v_result
    FROM public.reports r
    WHERE r.id = p_report_id
    LIMIT 1;

    RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.create_personnel_account(text, text, text, bigint) FROM public;
REVOKE ALL ON FUNCTION public.login_personnel_account(text, text) FROM public;
REVOKE ALL ON FUNCTION public.assign_report_personnel(bigint, bigint, jsonb) FROM public;
REVOKE ALL ON FUNCTION public.mark_personnel_assignment_done(bigint, bigint) FROM public;

GRANT EXECUTE ON FUNCTION public.create_personnel_account(text, text, text, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.login_personnel_account(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assign_report_personnel(bigint, bigint, jsonb) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mark_personnel_assignment_done(bigint, bigint) TO anon, authenticated;

COMMIT;
